language: node_js
node_js:
  - "8.1"
sudo: false
before_install:
  - rvm install 2.2.2
  - ./tool/before_install.sh
script: ./tool/travis.sh

branches:
  only:
    - gh-pages

after_success:
- echo "SUCCESS"
- git fetch
- git checkout master
# - echo "${SFTP_KEY}" | base64 --decode >/tmp/sftp_rsa
# - curl --ftp-create-dirs
#        -T filename
#        --key /tmp/sftp_rsa
#        sftp://${SFTP_USER}:${SFTP_PASSWORD}@example.com/directory/filename

# deploy:
#   provider: pages
#   skip-cleanup: true
#   github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
#   keep-history: true
#   on:
#     branch: master
    # branch: gh-pages

# deploy:
#   provider: script
#   script: bash deploy.sh
#   on:
#     branch: gh-pages